FROM python:3

MAINTAINER Memduh Çağrı Demir <memduhcagridemir@gmail.com>

RUN pip3 install tensorflow nltk
# RUN python3 -m nltk.downloader all

WORKDIR /root/de-identifier
CMD ["sleep", "infinity"]
